name: gelir_gider_takibi
description: "Maliyem Gelir Gider Takibi."
publish_to: "none"
version: 0.2.3+6

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Scroll Date Picker
  scroll_date_picker: ^3.7.3

  # Shared Preferences
  shared_preferences: ^2.2.2

  # Splash
  flutter_native_splash: ^2.3.11

  # Provider
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/image/
